name: nepali_calendar_flutter
description: Highly customizable Nepali Calendar package to display Nepali Bikram Sambat Calendar in your flutter applications.
version: 1.0.1

environment:
  sdk: ">=2.16.2 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  nepali_utils: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
